### ISSUE TITLE
responses are broken

### ISSUE THREAD

**Issue by mikesarfaty** [kylesferrazza/8ball#1]
I asked "is my name mike" and it said "outlook not so good" but my name is actually mike ????

**Comment by kylesferrazza** [comment]
This is intended behavior.

**Comment by kylesferrazza** [comment]
I asked "is this intended behavior?"

![image](https://user-images.githubusercontent.com/6677292/64960593-941f0900-d861-11e9-836d-c52cd9ebff22.png)
